"""
Investigation model module.

Defines the Pydantic V2 schema for the `investigations` MongoDB
collection, per ARCHITECTURE_V2.md Section 5 / Stage 5: an LLM-generated,
analyst-readable narrative for a given incident, summarizing the event
sequence and hypothesizing intent.
"""

from __future__ import annotations

from datetime import datetime, timezone

from bson import ObjectId
from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.models.raw_log import PyObjectId


class Investigation(BaseModel):
    """
    Schema for a document in the `investigations` collection.

    Represents the natural-language investigation narrative generated
    by the LLM for a single incident, along with provenance (model
    used, prompt version) and the model's self-reported confidence.
    """

    model_config = ConfigDict(
        populate_by_name=True,
        arbitrary_types_allowed=True,
        json_encoders={ObjectId: str},
    )

    id: PyObjectId = Field(
        default_factory=lambda: PyObjectId(ObjectId()),
        alias="_id",
        description="MongoDB document identifier.",
    )
    incident_ref: PyObjectId = Field(
        ...,
        description="Reference to the source document in `incidents`.",
    )
    narrative_text: str = Field(
        ...,
        min_length=1,
        description=(
            "Analyst-readable narrative summarizing the incident "
            "sequence, hypothesized intent, and flagged suspicious "
            "patterns, as generated by the LLM."
        ),
    )
    llm_model_used: str = Field(
        ...,
        min_length=1,
        description=(
            "Identifier of the LLM model that generated this narrative "
            "(e.g. 'gpt-4o'), for audit and reproducibility."
        ),
    )
    prompt_version: str = Field(
        ...,
        min_length=1,
        description=(
            "Version identifier of the system prompt template used to "
            "generate this narrative."
        ),
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Confidence in the generated investigation narrative, "
            "ranging from 0.0 (low) to 1.0 (high)."
        ),
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp at which this narrative was generated.",
    )

    @field_validator("generated_at")
    @classmethod
    def _ensure_timezone_aware(cls, value: datetime) -> datetime:
        """Normalize naive datetimes to UTC-aware datetimes."""
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value

    @field_validator("narrative_text")
    @classmethod
    def _strip_and_validate_narrative(cls, value: str) -> str:
        """Reject narratives that are empty or whitespace-only after stripping."""
        stripped = value.strip()
        if not stripped:
            raise ValueError("narrative_text must not be empty or whitespace-only")
        return stripped